services:
  mailman:
    build: .
    container_name: mailman
    restart: unless-stopped
    ports:
      - "8765:3000"
    environment:
      RESEND_API_KEY: ${RESEND_API_KEY}
      DEFAULT_FROM: ${DEFAULT_FROM:-noreply@yahoi.jp}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      PORT: 3000
    volumes:
      - ./.env:/app/.env
    networks:
      - mailnet

networks:
  mailnet:
    driver: bridge
